### ISSUE TITLE
feat(gatsby-plugin-fastify): Support new image cdn

### ISSUE THREAD

**Issue by cameronbraid** [gatsby-uc/plugins#194]
https://support.gatsbyjs.com/hc/en-us/articles/4426393233171

**Comment by cameronbraid** [comment]
I think all that is required is to implement a fastify version of the express dev server code in  https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-utils/src/polyfill-remote-file/http-routes.ts

**Comment by moonmeister** [comment]
This crossed my mind during the announcement. I need to get this to 1.0 before I have much time to invest in additional features like this. I do hope we can use what's used in the dev server though the fact that it's in the dev server makes me wonder. Will have to check that out.

**Comment by cameronbraid** [comment]
> though the fact that it's in the dev server makes me wonder

its in the dev server so that when running develop it uses a local _gatsby/image handler to do the transforms locally

**Comment by moonmeister** [comment]
I understand that...to expound on what I mean. The reason this plugin exists is because much of the code in the dev server is not as secure or performant as expected for a production grade server. I'm not sure whether this is the case for the implementation of the image conversion...but something that needs to be investigated and understood when deciding to reuse code vs re-implementing ourselves.
