### ISSUE TITLE
feat(gatsby-plugin-fastify): Support SSR routes with match paths

### ISSUE THREAD

**Issue by starrett67** [gatsby-uc/plugins#215]
## Is your feature request related to a problem? Please describe.
I'm trying to use this plugin and realized that the plugin does not support my serverside routes because they use match paths. Consider creating a page like this:
```
await createPage({
    path: `/furniture/product`,
    component: path.resolve(`./src/templates/ssr-product.jsx`),
    matchPath: `/furniture/product/*`,
  })
```
This creates an SSR page with a match path for all product description pages in my app. However, in the plugin code, it will treat any path with a match path as a clientside route?
https://github.com/gatsby-uc/plugins/blob/main/packages/gatsby-plugin-fastify/src/gatsby/clientSideRoutes.ts#L12

I don't think the plugin can sufficiently support ssr this way because having a match path has nothing to do with being client-side or server-side.

## Describe the solution you'd like

Support being able to render ssr or dsg pages if they have match paths. This is already supported by gatsby serve but I do not want to use gatsby serve in production.

**Comment by starrett67** [comment]
I went ahead and create a PR that I think will provide support for this feature:
https://github.com/gatsby-uc/plugins/pull/216

I tested this locally in my project and it works for serverside routes with match paths.

**Comment by moonmeister** [comment]
Hey, I'm trying to looking to this and get your PR merged. I"m not sure what feature of Gatsby this is you're referring to other than the standard [client only routes](https://www.gatsbyjs.com/docs/how-to/routing/client-only-routes-and-user-authentication/#how-to-configure-your-hosting-service-to-handle-client-only-routes). 

This feature does require server side support, but that's why the https://github.com/gatsby-uc/plugins/blob/main/packages/gatsby-plugin-fastify/src/gatsby/clientSideRoutes.ts plugin exists. Neither [`createPage`](https://www.gatsbyjs.com/docs/reference/config-files/actions/#createPage) or [`matchPath`](https://www.gatsbyjs.com/docs/gatsby-internals-terminology/#matchpath) docs suggest a version of this that's compatible with Server Side Rendering, but I have implemented the server side routing required as far as I know. 

It is possible there's some kind of bug happening or this is something woefully undocumented by Gatsby and I'm not understanding. If you could share you site code so I can understand better, or a  [ minimal reproduction][reproduction], that'd be great.

[reproduction]: https://gatsby.dev/reproduction
