### ISSUE TITLE
bug(gatsby-plugin-fastify): Not work on docker

### ISSUE THREAD

**Issue by NguyenKyThinh94** [gatsby-uc/plugins#265]
## Describe the bug
I set `GATSBY_SERVER_ADDRESS=0.0.0.0`
fastify can not access ip of docker network. Fastify always use `170.0.0.1`
And my nginx server can not access:
```logs
2022/10/04 02:42:20 [error] 24#24: *793 connect() failed (111: Connection refused) while connecting to upstream, client: 8.39.127.225, server: <domain>, request: "GET / HTTP/1.1", upstream: "http://172.25.0.7:3001/", host: <domain>
```

**Comment by moonmeister** [comment]
Hi {name}!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

In this case, at-least a docker file would be helpful.

Thanks! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by moonmeister** [comment]
ah, I figured it out! I documented this incorrectly. should be `GATSBY_SERVER_HOST`

**Comment by NguyenKyThinh94** [comment]
> ah, I figured it out! I documented this incorrectly. should be `GATSBY_SERVER_HOST`
OKay, Many thanks
