### ISSUE TITLE
bug(gatsby-plugin-fastify): Fastify style splat routes break windows

### ISSUE THREAD

**Issue by tsdexter** [gatsby-uc/plugins#270]
## Describe the bug

The repo cannot be cloned for contributing on Windows (see: https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows) ... I know, windows lol, but that's what I have at work and I can't bring in my macbook. 

When cloning, the errors below come up. Windows can't have `:` in the filename. Workarounds on stackoverflow are cumbersome and generally include renaming the files and/or opening security vulnerabilities. Is the `:` necessary? 

The offending files are in `https://github.com/gatsby-uc/plugins/tree/main/integration-tests/plugin-fastify/src/api/splat/:splat.js` and `https://github.com/gatsby-uc/plugins/tree/main/integration-tests/plugin-fastify/src/api/test1/:splat.js` 

```
Cloning into 'C:\Users\user\Documents\GitHub\gatsby-uc\plugins'...
remote: Enumerating objects: 6434, done.        
remote: Counting objects: 100% (508/508), done.        
remote: Compressing objects: 100% (226/226), done.        
remote: Total 6434 (delta 295), reused 462 (delta 263), pack-reused 5926        
Receiving objects: 100% (6434/6434), 16.46 MiB | 3.18 MiB/s, done.
Resolving deltas: 100% (2266/2266), done.
error: invalid path 'integration-tests/plugin-fastify/src/api/splat/:splat.js'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

## To Reproduce

clone repo in windows

## Expected behavior

clone works

## System Info

windows

**Comment by moonmeister** [comment]
🤔 So...I don't have a good answer. The issue here is Gatsby expects the file name to matter, and [Fastify uses the colon for splat routes](https://www.fastify.io/docs/latest/Reference/Routes/#url-building). We could potentially build something that converts from a [windows friendly format that Gatsby supports](https://www.gatsbyjs.com/docs/reference/functions/routing/). 

I should do some testing...to see what's possible...but not sure when I can get to this. The quickest way for this to work would probably to use WSL.

**Comment by tsdexter** [comment]
Thanks! I'll look into WSL in the meantime.
