### ISSUE TITLE
bug(gatsby-plugin-fastify): Doesn't work as expected for SSR pages

### ISSUE THREAD

**Issue by billypap1** [gatsby-uc/plugins#470]
## Describe the bug

I use gatsby-plugin-fastify (v0.13.3) for my gatsby app (gatsby v5.13.3)  but I have noticed 2 issues:

1) When you navigate on a page which is SSR, it reloads the page, so it's losing state.
2) In a page with ssr links, eg. a portfolio page with links to sub pages, I get this error:
404 Not Found - http://localhost:8080/page-data/productID/page-data.json  (On prefetch)

I tested the app with gatsby serve also, but I don't have any issue.

## To Reproduce

Create a page with sublinks and check network page in Chrome.

## Expected behavior

It shouldn't reload page and it should fetch page-data without any issue.

## System Info

Please provide information about your site via these means as possible:

gatsby-plugin-fastify (v0.13.3)
gatsby v5.13.3

Commands to run: 
yarn build
yarn gserve

**Comment by moonmeister** [comment]
Hey @billypap1, thanks for the report. I don't have a lot of time to work on this. Anytime I do have will probably be working to replace this plugin with the new "adapter" spec Gatsby implemented. That'll fix a lot of these weird little issues. 

I may have time the next couple days, I'll revisit that project and see what needs to be done. If you're interested in helping to get that across the line, let me know.

**Comment by moonmeister** [comment]
Sounds like it'll work.

**Comment by moonmeister** [comment]
This is the PR: https://github.com/gatsby-uc/plugins/pull/449 

Honestly it's been months...many months... So I don't remember the status. Adapters are  what they are. The problem is netlify is putting in 0 effort to Gatsby or that spec and there are known issues they are not addressing. I'm sure we could get something working on Fastify, how well may be in question. 

Because of Gatsby's slow death and my own personal life I'm putting almost no effort into any plugins. My honest recommendation would be to move to a new framework, but I recognize that's not always possible for folks. Spiritually I think Astro is probably the closest thing to Gatsby and Next is technically more familiar. 

That said `gatsby serve` is better than it was when I started this project, though it probably has its issues like the rest of Gatsby. It may be adequate for production though I'll leave that up to you to decide. 

If you're working for someone heavily invested in Gatsby who wants this adapter in top shape I'd be open to a contract to get this moving but otherwise I'll have little time for more than questions and PR reviews. 

Hope this helps, let me know if you have any questions.

**Comment by char-cole** [comment]
Thanks very much for the advice. I guess my intuition that Gatsby seemed weirdly abandoned was in fact correct. I will take a look and see about migrating my project.

**Comment by moonmeister** [comment]
Deprecating Package. See: #495 for more info.
