### ISSUE TITLE
bug(gatsby-source-strapi): can't get strapi component data

### ISSUE THREAD

**Issue by porleaaron** [gatsby-uc/plugins#476]
## Describe the bug

I can't get get strapi component data using graphql query on gatsby side.

## To Reproduce

This is my strapi  content-type
`
```
{
  "kind": "singleType",
  "collectionName": "indexpages",
  "info": {
    "singularName": "indexpage",
    "pluralName": "indexpages",
    "displayName": "indexpage"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "slug": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string"
    },
    "herosection": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "json"
    },
       "testimonials": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "component",
      "repeatable": true,
      "component": "shared.testimonial"
    }
  }
}
```

I want to fetch this on gatsby using the following query 

```
allStrapiIndexpage(filter: { locale: { eq: $locale } }) {
      edges {
        node {
          slug
          herosection {
            title1
            title2
         }
	 testimonials {
           name
           content
           image
         }
       }
     }
}

```
But it throws an error that **_testimonials_** does not exists in type StrapiIndexpage
So, I go to /__graphql endpoint and tried to find any graphql type for the **_testimonials_** which is the type "component" in 
strapi.

In gatsby-config, in plugin resolver section, I have
```
{
      resolve: "gatsby-source-strapi",
      options: {
        // apiURL: process.env.GATSBY_API_URL,
        apiURL: process.env.GATSBY_API_URL,
        accessToken: process.env.STRAPI_TOKEN,
        components: true
        ...
}
```

## Expected behavior

I need to fetch the data for testimonials

## System Info
"gatsby-source-strapi": "^3.3.3",
strapi version 4

Please provide information about your site via these means as possible:

**Comment by moonmeister** [comment]
Hi @porleaaron 

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction]. That said, work is done by volunteers here and no one has been regularly working on this plugin. We'd encourage you to do the reproduction work as it often helps you understand and solve your own problem. If this is truly a bug, then we'd invite you to contribute a fix.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by laurenskling** [comment]
You need to make sure the component relations get fetched. Strapi does not return relations/components by default. You need to `populate` them in the `queryParams`
